### PR TITLE
Update SpringAzureDemoApplication.java

### PR DESCRIPTION
**Pull request by Andrew44310**
Name change

### CODE REVIEW

**Review by imaadh0 — COMMENTED** [review]
No the code looks wrong

**Review by imaadh0 — CHANGES_REQUESTED** [review]
you need to add the background colour first

**Review by imaadh0 — COMMENTED** [review]
The code looks so wrong

**Comment by Andrew44310** [comment]
I will improve my code And really sorry for the mistake which i made in the code

**Pull request closed without merging**
